/**
 * Marlin 3D Printer Firmware
 * Copyright (c) 2020 MarlinFirmware
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */
#pragma once

#define CONFIGURATION_H_VERSION 02010300

// === MOTHERBOARD & COMMUNICATION ===
#ifndef MOTHERBOARD
  #define MOTHERBOARD BOARD_CREALITY_V4
#endif

#define CUSTOM_MACHINE_NAME "Ender3V2-422-MM"
#define SERIAL_PORT 1
#define NO_AUTO_ASSIGN_WARNING
#define BAUDRATE 250000

// === EXTRUDER ===
#define EXTRUDERS 1
#define DEFAULT_NOMINAL_FILAMENT_DIA 1.75

// === STEPPER DRIVERS ===
#define X_DRIVER_TYPE  TMC2208_STANDALONE
#define Y_DRIVER_TYPE  TMC2208_STANDALONE
#define Z_DRIVER_TYPE  TMC2208_STANDALONE
#define E0_DRIVER_TYPE TMC2208_STANDALONE

// === TEMPERATURE SENSORS ===
#define TEMP_SENSOR_0 1
#define TEMP_SENSOR_BED 1
#define TEMP_SENSOR_PROBE 0

// === HEATER THRESHOLDS ===
#define HEATER_0_MINTEMP 0
#define HEATER_0_MAXTEMP 275
#define BED_MINTEMP 0
#define BED_MAXTEMP 120
#define THERMAL_PROTECTION_HOTENDS
#define THERMAL_PROTECTION_BED

// === PID TEMPERATURE CONTROL ===
#define PIDTEMP
#define PIDTEMPBED
#define PID_FUNCTIONAL_RANGE 20
#define DEFAULT_Kp 21.73
#define DEFAULT_Ki 1.54
#define DEFAULT_Kd 76.55
#define DEFAULT_bedKp 46.88
#define DEFAULT_bedKi 1.54
#define DEFAULT_bedKd 706.64

// === EXTRUSION SAFETY ===
#define PREVENT_COLD_EXTRUSION
#define EXTRUDE_MINTEMP 180
#define PREVENT_LENGTHY_EXTRUDE
#define EXTRUDE_MAXLENGTH 1000

// === STEPPER DIRECTIONS ===
#define INVERT_X_DIR false
#define INVERT_Y_DIR false
#define INVERT_Z_DIR true
#define INVERT_E0_DIR false

// === ENDSTOPS ===
#define ENDSTOPPULLUPS
#define USE_XMIN_PLUG
#define USE_YMIN_PLUG
#define USE_ZMIN_PLUG
#define X_MIN_ENDSTOP_INVERTING false
#define Y_MIN_ENDSTOP_INVERTING false
#define Z_MIN_ENDSTOP_INVERTING false
#define X_MIN_ENDSTOP_HIT_STATE HIGH
#define Y_MIN_ENDSTOP_HIT_STATE HIGH
#define Z_MIN_ENDSTOP_HIT_STATE HIGH
#define Z_MIN_PROBE_ENDSTOP_HIT_STATE HIGH

// === PROBE SETUP (CR-Touch) ===
#define BLTOUCH
#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
#define USE_PROBE_FOR_Z_HOMING
#define NOZZLE_TO_PROBE_OFFSET { -44, -9, 0 }

// === Z-SAFE HOMING ===
#define Z_SAFE_HOMING
#define Z_SAFE_HOMING_X_POINT 117
#define Z_SAFE_HOMING_Y_POINT 117

// === BED LEVELING ===
#define AUTO_BED_LEVELING_BILINEAR
#define RESTORE_LEVELING_AFTER_G28
#define ENABLE_LEVELING_FADE_HEIGHT
#define DEFAULT_LEVELING_FADE_HEIGHT 10
#define GRID_MAX_POINTS_X 5
#define GRID_MAX_POINTS_Y 5
#define PROBING_MARGIN 10
#define XY_PROBE_FEEDRATE (200*60)
#define Z_PROBE_FEEDRATE_FAST (16*60)
#define Z_PROBE_FEEDRATE_SLOW (Z_PROBE_FEEDRATE_FAST / 2)
#define Z_CLEARANCE_DEPLOY_PROBE 10
#define Z_CLEARANCE_BETWEEN_PROBES 5
#define Z_CLEARANCE_MULTI_PROBE 5
#define Z_PROBE_ERROR_TOLERANCE 3
#define Z_PROBE_LOW_POINT -2
#define PROBE_OFFSET_XMIN -100
#define PROBE_OFFSET_XMAX 100
#define PROBE_OFFSET_YMIN -100
#define PROBE_OFFSET_YMAX 100

// === AXIS LIMITS ===
#define X_MIN_POS 0
#define Y_MIN_POS 0
#define Z_MIN_POS 0
#define X_MAX_POS 248
#define Y_MAX_POS 231
#define Z_MAX_POS 250
#define X_BED_SIZE 230
#define Y_BED_SIZE 230

// === SOFTWARE ENDSTOPS ===
#define MIN_SOFTWARE_ENDSTOPS
#define MAX_SOFTWARE_ENDSTOPS

// === HOMING ===
#define X_HOME_DIR -1
#define Y_HOME_DIR -1
#define Z_HOME_DIR -1
#define HOMING_FEEDRATE_MM_M { (50*60), (50*60), (10*60) }
#define Z_AFTER_HOMING 5
#define HOME_AFTER_DEACTIVATE
#define EDITABLE_HOMING_FEEDRATE
#define VALIDATE_HOMING_ENDSTOPS

// === MOTION ===
#define DEFAULT_AXIS_STEPS_PER_UNIT { 80, 80, 400, 93 }
#define DEFAULT_MAX_FEEDRATE { 500, 500, 10, 45 }
#define DEFAULT_MAX_ACCELERATION { 500, 500, 100, 1000 }
#define DEFAULT_ACCELERATION 500
#define DEFAULT_RETRACT_ACCELERATION 800
#define DEFAULT_TRAVEL_ACCELERATION 1000
#define JUNCTION_DEVIATION_MM 0.1
#define S_CURVE_ACCELERATION

// === TEMPORARY DISABLES (Memory Optimization) ===
//#define MESH_BED_LEVELING
//#define ARC_SUPPORT
//#define LIN_ADVANCE
//#define FILAMENT_RUNOUT_SENSOR
//#define POWER_LOSS_RECOVERY
//#define ADVANCED_PAUSE_FEATURE

// === EEPROM ===
#define EEPROM_SETTINGS
#define EEPROM_CHITCHAT
#define EEPROM_AUTO_INIT
//#define EEPROM_INIT_NOW

// === LCD & UI ===
#define DWIN_LCD_PROUI
#define USE_STOCK_DWIN_SET
#define PROUI_EX 1
#define LCD_LANGUAGE en
#define ENCODER_PULSES_PER_STEP 4
#define ENCODER_STEPS_PER_MENU_ITEM 1
#define LCD_FEEDBACK_FREQUENCY_DURATION_MS 2
#define LCD_FEEDBACK_FREQUENCY_HZ 5000

// === NOZZLE PARK ===
#define NOZZLE_PARK_FEATURE
#define NOZZLE_PARK_POINT { (X_BED_SIZE + 10), (Y_MAX_POS - 10), 20 }
#define NOZZLE_PARK_Z_RAISE_MIN 0
#define NOZZLE_PARK_XY_FEEDRATE 100
#define NOZZLE_PARK_Z_FEEDRATE 5

// === PRINT STATS ===
#define PRINTJOB_TIMER_AUTOSTART
#define PRINTCOUNTER
#define PRINTCOUNTER_SAVE_INTERVAL 60

// === SD CARD ===
#define SDSUPPORT

// === MISC ===
#define FAN_SOFT_PWM
#define SOFT_PWM_SCALE 0
#define HOST_KEEPALIVE_FEATURE
#define DEFAULT_KEEPALIVE_INTERVAL 2
#define BUSY_WHILE_HEATING
#define SERVO_DELAY { 300 }
#define PREHEAT_BEFORE_LEVELING
#define LEVELING_NOZZLE_TEMP 175
#define LEVELING_BED_TEMP 50

// === PREHEAT SETTINGS ===
#define PREHEAT_1_LABEL "PLA"
#define PREHEAT_1_TEMP_HOTEND 195
#define PREHEAT_1_TEMP_BED 60
#define PREHEAT_1_FAN_SPEED 128

#define PREHEAT_2_LABEL "ABS"
#define PREHEAT_2_TEMP_HOTEND 240
#define PREHEAT_2_TEMP_BED 90
#define PREHEAT_2_FAN_SPEED 128

#endif // CONFIGURATION_H
